import type { Operator, Tour, Review, BlogPost, TourAvailability, Booking, Dispute } from '@/types'

export const MOCK_OPERATORS: Operator[] = [
  {
    id: 'op-1',
    user_id: 'user-op-1',
    business_name: 'Namiri Tours Mwanza',
    slug: 'namiri-tours-mwanza',
    description:
      'Namiri Tours Mwanza is a Western Tanzania specialist with over 12 years of experience guiding travelers through Mahale Mountains, Katavi, and Rubondo Island. Our local guides know the chimpanzee trekking trails better than anyone.',
    logo_url: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=500&fit=crop',
    location: 'Mwanza, Tanzania',
    city: 'Mwanza',
    regions: ['Western Circuit', 'Lake Victoria'],
    certifications: ['TATO Member', 'TTB Licensed'],
    tato_member: true,
    ttb_licensed: true,
    ttb_licence_number: 'TTB-2014-0091',
    phone: '+255754000001',
    whatsapp: '+255754000001',
    email: 'info@namiritours.co.tz',
    flutterwave_subaccount_id: null,
    flutterwave_onboarding_complete: false,
    avg_rating: 4.9,
    total_reviews: 86,
    total_bookings: 412,
    status: 'approved',
    featured: true,
    verified_at: '2024-02-01T00:00:00Z',
    created_at: '2023-11-01T00:00:00Z',
  },
  {
    id: 'op-2',
    user_id: 'user-op-2',
    business_name: 'Shayona Safaris Mwanza',
    slug: 'shayona-safaris-mwanza',
    description:
      'Shayona Safaris Mwanza offers premium small-group safaris across Northern and Western Tanzania, with a focus on Serengeti migration tracking and Ngorongoro Crater day trips. Family-run since 2009.',
    logo_url: 'https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=1200&h=500&fit=crop',
    location: 'Mwanza, Tanzania',
    city: 'Mwanza',
    regions: ['Northern Circuit', 'Western Circuit'],
    certifications: ['TATO Member', 'TTB Licensed'],
    tato_member: true,
    ttb_licensed: true,
    ttb_licence_number: 'TTB-2009-0034',
    phone: '+255754000002',
    whatsapp: '+255754000002',
    email: 'bookings@shayonasafaris.co.tz',
    flutterwave_subaccount_id: null,
    flutterwave_onboarding_complete: false,
    avg_rating: 4.8,
    total_reviews: 134,
    total_bookings: 601,
    status: 'approved',
    featured: true,
    verified_at: '2023-06-15T00:00:00Z',
    created_at: '2022-09-12T00:00:00Z',
  },
  {
    id: 'op-3',
    user_id: 'user-op-3',
    business_name: 'Access2Tanzania Dar',
    slug: 'access2tanzania-dar',
    description:
      'Access2Tanzania Dar connects travelers to Zanzibar beach escapes, Kilimanjaro climbs, and classic Northern Circuit safaris from our Dar es Salaam base, with full logistics support across the country.',
    logo_url: 'https://images.unsplash.com/photo-1500051638674-ff996a0ec29e?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1200&h=500&fit=crop',
    location: 'Dar es Salaam, Tanzania',
    city: 'Dar es Salaam',
    regions: ['Zanzibar', 'Kilimanjaro', 'Northern Circuit'],
    certifications: ['TTB Licensed'],
    tato_member: false,
    ttb_licensed: true,
    ttb_licence_number: 'TTB-2017-0182',
    phone: '+255754000003',
    whatsapp: '+255754000003',
    email: 'hello@access2tanzania.co.tz',
    flutterwave_subaccount_id: null,
    flutterwave_onboarding_complete: false,
    avg_rating: 4.7,
    total_reviews: 98,
    total_bookings: 355,
    status: 'approved',
    featured: false,
    verified_at: '2024-01-10T00:00:00Z',
    created_at: '2023-04-20T00:00:00Z',
  },
]

export const MOCK_TOURS: Tour[] = [
  {
    id: 'tour-1',
    operator_id: 'op-1',
    slug: 'mahale-chimpanzee-trek-5-days',
    title: 'Mahale Mountains Chimpanzee Trek — 5 Days',
    description:
      'Trek through the remote rainforests of Mahale Mountains National Park to track wild chimpanzees on the shores of Lake Tanganyika. Includes boat transfers, forest guides, and beach camp accommodation.',
    tour_type: 'safari',
    regions: ['Western Circuit'],
    duration_days: 5,
    duration_nights: 4,
    min_group: 2,
    max_group: 8,
    price_usd: 2800,
    price_tzs: 7280000,
    difficulty: 'challenging',
    highlights: ['Wild chimpanzee tracking', 'Lake Tanganyika beach camp', 'Remote rainforest hiking', 'Small group, expert guides'],
    inclusions: ['All park fees', 'Boat transfers', 'Full board accommodation', 'Professional guide', 'Domestic flights from Mwanza'],
    exclusions: ['International flights', 'Travel insurance', 'Tips and gratuities', 'Alcoholic beverages'],
    itinerary: [
      { day: 1, title: 'Arrival & Boat Transfer', activities: 'Fly to Mahale airstrip, boat transfer to camp', accommodation: 'Mahale Beach Camp', accommodation_type: 'Tented camp', meals: { breakfast: false, lunch: true, dinner: true }, transport: 'Light aircraft + boat' },
      { day: 2, title: 'Chimp Trekking Day 1', activities: 'Morning trek with rangers to locate chimpanzee groups', accommodation: 'Mahale Beach Camp', accommodation_type: 'Tented camp', meals: { breakfast: true, lunch: true, dinner: true }, transport: 'On foot' },
      { day: 3, title: 'Chimp Trekking Day 2', activities: 'Second trek attempt, afternoon lake swim', accommodation: 'Mahale Beach Camp', accommodation_type: 'Tented camp', meals: { breakfast: true, lunch: true, dinner: true }, transport: 'On foot' },
      { day: 4, title: 'Forest Walk & Relaxation', activities: 'Gentle forest walk, free afternoon on the beach', accommodation: 'Mahale Beach Camp', accommodation_type: 'Tented camp', meals: { breakfast: true, lunch: true, dinner: true }, transport: 'On foot' },
      { day: 5, title: 'Departure', activities: 'Boat transfer and flight back to Mwanza', accommodation: 'N/A', accommodation_type: 'N/A', meals: { breakfast: true, lunch: false, dinner: false }, transport: 'Boat + light aircraft' },
    ],
    addons: [
      { id: 'addon-1', name: 'Extra trekking day', price_usd: 350, description: 'Add an additional chimpanzee tracking day' },
      { id: 'addon-2', name: 'Private boat charter', price_usd: 200, description: 'Private rather than shared boat transfer' },
    ],
    cancellation_policy: 'Free cancellation up to 30 days before travel. 50% refund 15-29 days before. No refund within 14 days.',
    languages: ['en', 'sw'],
    images: [
      { url: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=900&h=600&fit=crop', alt: 'Mahale Mountains forest' },
      { url: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=900&h=600&fit=crop', alt: 'Lake Tanganyika shoreline' },
    ],
    is_instant_book: true,
    is_active: true,
    is_featured: true,
    avg_rating: 5.0,
    total_reviews: 22,
    total_bookings: 58,
    meta_title: 'Mahale Mountains Chimpanzee Trek — 5 Day Tour',
    meta_description: 'Track wild chimpanzees in Mahale Mountains National Park on this 5-day Western Tanzania adventure.',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'tour-2',
    operator_id: 'op-1',
    slug: 'katavi-wilderness-safari-4-days',
    title: 'Katavi Wilderness Safari — 4 Days',
    description:
      "Explore one of Africa's most untouched parks. Katavi National Park offers massive hippo pools, huge buffalo herds, and incredible predator sightings with almost no other tourists in sight.",
    tour_type: 'safari',
    regions: ['Western Circuit'],
    duration_days: 4,
    duration_nights: 3,
    min_group: 2,
    max_group: 6,
    price_usd: 2200,
    price_tzs: 5720000,
    difficulty: 'moderate',
    highlights: ['Massive hippo pools', 'Huge buffalo herds', 'Low tourist density', 'Authentic bush camping'],
    inclusions: ['All park fees', 'Full board accommodation', '4x4 safari vehicle', 'Professional guide', 'Domestic flights from Mwanza'],
    exclusions: ['International flights', 'Travel insurance', 'Tips and gratuities'],
    itinerary: [
      { day: 1, title: 'Arrival & First Game Drive', activities: 'Fly into Katavi, afternoon game drive', accommodation: 'Katavi Bush Camp', accommodation_type: 'Tented camp', meals: { breakfast: false, lunch: true, dinner: true }, transport: 'Light aircraft + 4x4' },
      { day: 2, title: 'Full Day Game Drives', activities: 'Morning and afternoon drives around the floodplains', accommodation: 'Katavi Bush Camp', accommodation_type: 'Tented camp', meals: { breakfast: true, lunch: true, dinner: true }, transport: '4x4' },
      { day: 3, title: 'Hippo Pools & Walking Safari', activities: 'Visit famous hippo pools, guided walking safari', accommodation: 'Katavi Bush Camp', accommodation_type: 'Tented camp', meals: { breakfast: true, lunch: true, dinner: true }, transport: '4x4 + on foot' },
      { day: 4, title: 'Departure', activities: 'Final morning drive, flight back to Mwanza', accommodation: 'N/A', accommodation_type: 'N/A', meals: { breakfast: true, lunch: false, dinner: false }, transport: 'Light aircraft' },
    ],
    addons: [{ id: 'addon-3', name: 'Walking safari extension', price_usd: 150, description: 'Extra half-day guided walking safari' }],
    cancellation_policy: 'Free cancellation up to 30 days before travel. 50% refund 15-29 days before. No refund within 14 days.',
    languages: ['en', 'sw'],
    images: [
      { url: 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=900&h=600&fit=crop', alt: 'Katavi floodplain' },
      { url: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=900&h=600&fit=crop', alt: 'Buffalo herd' },
    ],
    is_instant_book: true,
    is_active: true,
    is_featured: true,
    avg_rating: 4.9,
    total_reviews: 17,
    total_bookings: 41,
    meta_title: 'Katavi Wilderness Safari — 4 Day Tour',
    meta_description: "Discover Katavi National Park's untouched wilderness on this 4-day Western Tanzania safari.",
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'tour-3',
    operator_id: 'op-2',
    slug: 'serengeti-migration-safari-7-days',
    title: 'Serengeti Great Migration Safari — 7 Days',
    description:
      'A comprehensive 7-day journey through the Serengeti ecosystem timed to the Great Migration, with stops at Ngorongoro Crater and Lake Manyara. Premium lodges and expert migration tracking.',
    tour_type: 'safari',
    regions: ['Northern Circuit'],
    duration_days: 7,
    duration_nights: 6,
    min_group: 1,
    max_group: 12,
    price_usd: 3450,
    price_tzs: 8970000,
    difficulty: 'easy',
    highlights: ['Great Migration tracking', 'Ngorongoro Crater descent', 'Lake Manyara birdlife', 'Luxury lodge stays'],
    inclusions: ['All park fees', 'Full board accommodation', '4x4 safari vehicle with pop-up roof', 'Professional guide', 'Airport transfers'],
    exclusions: ['International flights', 'Travel insurance', 'Tips and gratuities', 'Premium drinks'],
    itinerary: [
      { day: 1, title: 'Arrival in Arusha', activities: 'Airport pickup, briefing dinner', accommodation: 'Arusha Lodge', accommodation_type: 'Lodge', meals: { breakfast: false, lunch: false, dinner: true }, transport: 'Private vehicle' },
      { day: 2, title: 'Lake Manyara', activities: 'Game drive in Lake Manyara National Park', accommodation: 'Manyara Lodge', accommodation_type: 'Lodge', meals: { breakfast: true, lunch: true, dinner: true }, transport: '4x4' },
      { day: 3, title: 'Serengeti Central', activities: 'Drive to Serengeti, afternoon game drive', accommodation: 'Serengeti Camp', accommodation_type: 'Tented camp', meals: { breakfast: true, lunch: true, dinner: true }, transport: '4x4' },
      { day: 4, title: 'Migration Tracking', activities: 'Full day following migration herds', accommodation: 'Serengeti Camp', accommodation_type: 'Tented camp', meals: { breakfast: true, lunch: true, dinner: true }, transport: '4x4' },
      { day: 5, title: 'Serengeti North', activities: 'Drive north for river crossing season', accommodation: 'Serengeti North Camp', accommodation_type: 'Tented camp', meals: { breakfast: true, lunch: true, dinner: true }, transport: '4x4' },
      { day: 6, title: 'Ngorongoro Crater', activities: 'Descend into the crater for big five game drive', accommodation: 'Ngorongoro Lodge', accommodation_type: 'Lodge', meals: { breakfast: true, lunch: true, dinner: true }, transport: '4x4' },
      { day: 7, title: 'Departure', activities: 'Morning drive, transfer to Kilimanjaro airport', accommodation: 'N/A', accommodation_type: 'N/A', meals: { breakfast: true, lunch: false, dinner: false }, transport: 'Private vehicle' },
    ],
    addons: [
      { id: 'addon-4', name: 'Hot air balloon safari', price_usd: 600, description: 'Sunrise balloon flight over the Serengeti' },
      { id: 'addon-5', name: 'Maasai village visit', price_usd: 80, description: 'Cultural visit to a local Maasai community' },
    ],
    cancellation_policy: 'Free cancellation up to 45 days before travel. 50% refund 20-44 days before. No refund within 19 days.',
    languages: ['en', 'fr', 'sw'],
    images: [
      { url: 'https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=900&h=600&fit=crop', alt: 'Serengeti plains' },
      { url: 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=900&h=600&fit=crop', alt: 'Wildebeest migration' },
    ],
    is_instant_book: true,
    is_active: true,
    is_featured: true,
    avg_rating: 4.95,
    total_reviews: 64,
    total_bookings: 211,
    meta_title: 'Serengeti Great Migration Safari — 7 Day Tour',
    meta_description: 'Track the Great Migration across the Serengeti and Ngorongoro Crater on this 7-day premium safari.',
    created_at: '2023-12-01T00:00:00Z',
  },
  {
    id: 'tour-4',
    operator_id: 'op-2',
    slug: 'ngorongoro-crater-day-trip',
    title: 'Ngorongoro Crater Day Trip',
    description:
      "A full-day excursion into the Ngorongoro Crater, often called Africa's Eden. See dense wildlife concentrations including lion, elephant, and the rare black rhino, all within the crater walls.",
    tour_type: 'day-trip',
    regions: ['Northern Circuit'],
    duration_days: 1,
    duration_nights: 0,
    min_group: 1,
    max_group: 6,
    price_usd: 320,
    price_tzs: 832000,
    difficulty: 'easy',
    highlights: ['Big Five game viewing', 'Crater floor descent', 'Flamingo lake', 'Picnic lunch with a view'],
    inclusions: ['Park fees', 'Crater service fee', '4x4 vehicle', 'Professional guide', 'Picnic lunch'],
    exclusions: ['Accommodation', 'International flights', 'Tips'],
    itinerary: [
      { day: 1, title: 'Crater Day Trip', activities: 'Early descent into the crater, full day game viewing, picnic lunch by the hippo pool', accommodation: 'N/A', accommodation_type: 'N/A', meals: { breakfast: false, lunch: true, dinner: false }, transport: '4x4' },
    ],
    addons: [],
    cancellation_policy: 'Free cancellation up to 7 days before travel.',
    languages: ['en', 'sw'],
    images: [{ url: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=900&h=600&fit=crop', alt: 'Ngorongoro Crater' }],
    is_instant_book: true,
    is_active: true,
    is_featured: false,
    avg_rating: 4.8,
    total_reviews: 39,
    total_bookings: 178,
    meta_title: 'Ngorongoro Crater Day Trip',
    meta_description: 'Spend a full day exploring the wildlife-rich floor of the Ngorongoro Crater.',
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: 'tour-5',
    operator_id: 'op-3',
    slug: 'kilimanjaro-machame-route-8-days',
    title: 'Kilimanjaro Machame Route Climb — 8 Days',
    description:
      'Summit Africa\'s tallest peak via the scenic Machame Route, known for its rainforest start and dramatic ridge walks. Includes full camping equipment, porters, and acclimatization day.',
    tour_type: 'trekking',
    regions: ['Kilimanjaro'],
    duration_days: 8,
    duration_nights: 7,
    min_group: 1,
    max_group: 10,
    price_usd: 2650,
    price_tzs: 6890000,
    difficulty: 'challenging',
    highlights: ['Summit Uhuru Peak', 'Rainforest to glacier zones', 'Extra acclimatization day', 'Experienced summit guides'],
    inclusions: ['Park fees', 'All camping equipment', 'Porters and guides', 'Full board on mountain', 'Pre-climb briefing'],
    exclusions: ['International flights', 'Travel insurance', 'Tips for guides and porters', 'Personal climbing gear'],
    itinerary: [
      { day: 1, title: 'Machame Gate to Machame Camp', activities: 'Trek through montane rainforest', accommodation: 'Machame Camp', accommodation_type: 'Camping', meals: { breakfast: true, lunch: true, dinner: true }, transport: 'On foot' },
      { day: 2, title: 'Machame to Shira Camp', activities: 'Trek into moorland zone', accommodation: 'Shira Camp', accommodation_type: 'Camping', meals: { breakfast: true, lunch: true, dinner: true }, transport: 'On foot' },
      { day: 3, title: 'Shira to Barranco Camp', activities: 'Acclimatization hike via Lava Tower', accommodation: 'Barranco Camp', accommodation_type: 'Camping', meals: { breakfast: true, lunch: true, dinner: true }, transport: 'On foot' },
      { day: 4, title: 'Barranco Wall to Karanga', activities: 'Climb the Barranco Wall', accommodation: 'Karanga Camp', accommodation_type: 'Camping', meals: { breakfast: true, lunch: true, dinner: true }, transport: 'On foot' },
      { day: 5, title: 'Karanga to Barafu Camp', activities: 'Trek to base camp, early rest', accommodation: 'Barafu Camp', accommodation_type: 'Camping', meals: { breakfast: true, lunch: true, dinner: true }, transport: 'On foot' },
      { day: 6, title: 'Summit Day — Uhuru Peak', activities: 'Midnight summit push, descend to Mweka Camp', accommodation: 'Mweka Camp', accommodation_type: 'Camping', meals: { breakfast: true, lunch: true, dinner: true }, transport: 'On foot' },
      { day: 7, title: 'Mweka Camp to Gate', activities: 'Final descent through rainforest', accommodation: 'Moshi hotel', accommodation_type: 'Hotel', meals: { breakfast: true, lunch: true, dinner: false }, transport: 'On foot + vehicle' },
      { day: 8, title: 'Departure', activities: 'Transfer to Kilimanjaro airport', accommodation: 'N/A', accommodation_type: 'N/A', meals: { breakfast: true, lunch: false, dinner: false }, transport: 'Private vehicle' },
    ],
    addons: [{ id: 'addon-6', name: 'Private summit guide', price_usd: 250, description: 'Dedicated 1-on-1 summit guide' }],
    cancellation_policy: 'Free cancellation up to 60 days before travel. 50% refund 30-59 days before. No refund within 29 days.',
    languages: ['en', 'sw'],
    images: [{ url: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?w=900&h=600&fit=crop', alt: 'Kilimanjaro summit' }],
    is_instant_book: false,
    is_active: true,
    is_featured: true,
    avg_rating: 4.85,
    total_reviews: 28,
    total_bookings: 73,
    meta_title: 'Kilimanjaro Machame Route Climb — 8 Day Trek',
    meta_description: 'Summit Mount Kilimanjaro via the scenic Machame Route on this 8-day guided trek.',
    created_at: '2023-10-05T00:00:00Z',
  },
  {
    id: 'tour-6',
    operator_id: 'op-3',
    slug: 'zanzibar-beach-escape-5-days',
    title: 'Zanzibar Beach Escape — 5 Days',
    description:
      'Unwind on the white-sand beaches of Zanzibar with a blend of relaxation and culture — Stone Town tours, a spice farm visit, and a sunset dhow cruise included.',
    tour_type: 'beach',
    regions: ['Zanzibar'],
    duration_days: 5,
    duration_nights: 4,
    min_group: 1,
    max_group: 14,
    price_usd: 1450,
    price_tzs: 3770000,
    difficulty: 'easy',
    highlights: ['Stone Town UNESCO tour', 'Spice farm visit', 'Sunset dhow cruise', 'Beachfront resort stay'],
    inclusions: ['Airport transfers', 'Beachfront accommodation', 'Daily breakfast', 'Stone Town guided tour', 'Spice farm tour', 'Dhow cruise'],
    exclusions: ['International flights', 'Lunch and dinner (except cruise)', 'Travel insurance', 'Water sports'],
    itinerary: [
      { day: 1, title: 'Arrival', activities: 'Airport transfer, check-in, beach relaxation', accommodation: 'Zanzibar Beach Resort', accommodation_type: 'Resort', meals: { breakfast: false, lunch: false, dinner: false }, transport: 'Private vehicle' },
      { day: 2, title: 'Stone Town Tour', activities: 'Guided walking tour of historic Stone Town', accommodation: 'Zanzibar Beach Resort', accommodation_type: 'Resort', meals: { breakfast: true, lunch: false, dinner: false }, transport: 'Private vehicle' },
      { day: 3, title: 'Spice Farm Visit', activities: 'Morning spice farm tour, afternoon free', accommodation: 'Zanzibar Beach Resort', accommodation_type: 'Resort', meals: { breakfast: true, lunch: false, dinner: false }, transport: 'Private vehicle' },
      { day: 4, title: 'Sunset Dhow Cruise', activities: 'Free day on the beach, evening dhow cruise with dinner', accommodation: 'Zanzibar Beach Resort', accommodation_type: 'Resort', meals: { breakfast: true, lunch: false, dinner: true }, transport: 'Dhow boat' },
      { day: 5, title: 'Departure', activities: 'Free morning, airport transfer', accommodation: 'N/A', accommodation_type: 'N/A', meals: { breakfast: true, lunch: false, dinner: false }, transport: 'Private vehicle' },
    ],
    addons: [
      { id: 'addon-7', name: 'Snorkeling trip to Mnemba Atoll', price_usd: 90, description: 'Half-day snorkeling excursion' },
      { id: 'addon-8', name: 'Couples spa package', price_usd: 140, description: 'Beachfront spa treatment for two' },
    ],
    cancellation_policy: 'Free cancellation up to 14 days before travel. 50% refund 7-13 days before. No refund within 6 days.',
    languages: ['en', 'sw', 'fr'],
    images: [{ url: 'https://images.unsplash.com/photo-1591025207163-942350e47db2?w=900&h=600&fit=crop', alt: 'Zanzibar beach' }],
    is_instant_book: true,
    is_active: true,
    is_featured: true,
    avg_rating: 4.9,
    total_reviews: 51,
    total_bookings: 264,
    meta_title: 'Zanzibar Beach Escape — 5 Day Tour',
    meta_description: 'Relax on Zanzibar\'s white-sand beaches with Stone Town tours and a sunset dhow cruise.',
    created_at: '2024-03-01T00:00:00Z',
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    booking_id: 'bk-1',
    tour_id: 'tour-1',
    operator_id: 'op-1',
    tourist_id: null,
    tourist_name: 'Sarah Mitchell',
    tourist_country: 'US',
    rating: 5,
    title: 'Once-in-a-lifetime chimp trekking',
    body: 'Tracking wild chimpanzees through the Mahale rainforest was unforgettable. Our guide knew exactly where to find them, and the beach camp on Lake Tanganyika was the perfect place to relax afterward. Namiri Tours handled every detail flawlessly.',
    photos: [],
    operator_response: 'Thank you Sarah! We loved hosting you and the chimps clearly approved too.',
    operator_responded_at: '2024-05-02T00:00:00Z',
    is_verified: true,
    is_published: true,
    created_at: '2024-04-28T00:00:00Z',
  },
  {
    id: 'rev-2',
    booking_id: 'bk-2',
    tour_id: 'tour-3',
    operator_id: 'op-2',
    tourist_id: null,
    tourist_name: 'James Whitfield',
    tourist_country: 'GB',
    rating: 5,
    title: 'Witnessed the river crossing!',
    body: 'We timed our trip with Shayona Safaris perfectly and got to see a full wildebeest river crossing in the Serengeti. The guide was incredibly knowledgeable and the camps were comfortable even in the remote north.',
    photos: [],
    operator_response: null,
    operator_responded_at: null,
    is_verified: true,
    is_published: true,
    created_at: '2024-08-15T00:00:00Z',
  },
  {
    id: 'rev-3',
    booking_id: 'bk-3',
    tour_id: 'tour-6',
    operator_id: 'op-3',
    tourist_id: null,
    tourist_name: 'Lena Fischer',
    tourist_country: 'DE',
    rating: 5,
    title: 'Perfect end to our Tanzania trip',
    body: 'After two weeks of safari, Zanzibar was exactly the relaxation we needed. The dhow cruise at sunset was magical and Stone Town was full of history. Access2Tanzania made the booking and transfers seamless.',
    photos: [],
    operator_response: 'So glad you enjoyed it, Lena! Karibu tena (welcome back anytime).',
    operator_responded_at: '2024-06-10T00:00:00Z',
    is_verified: true,
    is_published: true,
    created_at: '2024-06-05T00:00:00Z',
  },
  {
    id: 'rev-4',
    booking_id: 'bk-4',
    tour_id: 'tour-2',
    operator_id: 'op-1',
    tourist_id: null,
    tourist_name: 'Carlos Rivera',
    tourist_country: 'ES',
    rating: 5,
    title: 'Untouched wilderness, incredible wildlife',
    body: 'Katavi felt like we had the entire park to ourselves. We saw more buffalo in one afternoon than we expected to see the whole trip, and the hippo pools were unreal. Highly recommend for travelers wanting something off the beaten path.',
    photos: [],
    operator_response: null,
    operator_responded_at: null,
    is_verified: true,
    is_published: true,
    created_at: '2024-07-22T00:00:00Z',
  },
  {
    id: 'rev-5',
    booking_id: 'bk-5',
    tour_id: 'tour-5',
    operator_id: 'op-3',
    tourist_id: null,
    tourist_name: 'Aiko Tanaka',
    tourist_country: 'JP',
    rating: 5,
    title: 'Made it to Uhuru Peak!',
    body: 'The Machame route guides from Access2Tanzania got our whole group safely to the summit. The acclimatization day really helped, and the porters were unbelievably hard-working. An experience I will never forget.',
    photos: [],
    operator_response: 'Congratulations again on the summit, Aiko! Well earned.',
    operator_responded_at: '2024-03-18T00:00:00Z',
    is_verified: true,
    is_published: true,
    created_at: '2024-03-14T00:00:00Z',
  },
  {
    id: 'rev-6',
    booking_id: 'bk-6',
    tour_id: 'tour-4',
    operator_id: 'op-2',
    tourist_id: null,
    tourist_name: 'Emma Johansson',
    tourist_country: 'SE',
    rating: 5,
    title: 'Africa\'s Eden lives up to the name',
    body: 'We saw lions, elephants, and even a black rhino all in one day inside the crater. Shayona Safaris picked the perfect picnic spot by the hippo pool. A must-do day trip from Arusha.',
    photos: [],
    operator_response: null,
    operator_responded_at: null,
    is_verified: true,
    is_published: true,
    created_at: '2024-09-02T00:00:00Z',
  },
]

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    slug: 'mahale-chimpanzee-guide',
    title: 'Mahale Mountains: The Complete Guide to Chimpanzee Trekking',
    excerpt: 'Everything you need to know about trekking to see wild chimpanzees on the shores of Lake Tanganyika, from getting there to what to pack.',
    body: 'Full article content about Mahale Mountains chimpanzee trekking. Mahale Mountains National Park sits on the remote eastern shore of Lake Tanganyika and is one of only two places in Tanzania where you can trek to see wild, habituated chimpanzees. Access is by charter flight only, which keeps visitor numbers low and sightings intimate. Trekking difficulty varies by day — some mornings the chimps are found within twenty minutes of camp, other days require several hours of steep forest hiking. Pack light, breathable layers, sturdy boots, and a head net for the rainforest insects.',
    author: 'LifeGranted Adventures Team',
    category: 'Guides',
    tags: ['Mahale', 'Western Tanzania', 'Chimpanzees'],
    featured_image: 'https://images.unsplash.com/photo-1534476478164-b15fec4f091c?w=800&h=500&fit=crop',
    seo_title: 'Mahale Mountains: The Complete Guide to Chimpanzee Trekking | LifeGranted Adventures',
    seo_description: 'Plan your Mahale Mountains chimpanzee trek with our complete travel guide.',
    is_published: true,
    published_at: '2024-05-10T00:00:00Z',
    created_at: '2024-05-08T00:00:00Z',
  },
  {
    id: 'blog-2',
    slug: 'western-vs-northern-circuit',
    title: 'Western Tanzania vs Northern Circuit: Which Safari Is Right for You?',
    excerpt: 'Katavi, Mahale, and Rubondo Island offer the wildlife of the Serengeti without the crowds — but the Northern Circuit has the migration. Here is how to choose.',
    body: 'Full article content comparing Western Tanzania and the Northern Circuit. The Northern Circuit — Serengeti, Ngorongoro, Tarangire — delivers the highest density of wildlife and the famous Great Migration, with excellent infrastructure and shorter flights. The Western Circuit — Mahale, Katavi, Rubondo, Gombe — trades some of that density for total exclusivity: you may not see another vehicle for days, and chimpanzee trekking is unique to the west. Budget travelers and first-timers often prefer the north; repeat visitors and those seeking solitude gravitate west.',
    author: 'LifeGranted Adventures Team',
    category: 'Guides',
    tags: ['Western Tanzania', 'Northern Circuit', 'Trip Planning'],
    featured_image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&h=500&fit=crop',
    seo_title: 'Western Tanzania vs Northern Circuit: Which Safari Is Right for You?',
    seo_description: 'Compare the Western and Northern Tanzania safari circuits to plan your ideal trip.',
    is_published: true,
    published_at: '2024-04-22T00:00:00Z',
    created_at: '2024-04-20T00:00:00Z',
  },
  {
    id: 'blog-3',
    slug: 'tanzania-safari-cost',
    title: 'How Much Does a Tanzania Safari Cost? A Real Breakdown',
    excerpt: 'Park fees, charter flights, lodge rates, and guide costs — here is exactly where your safari budget goes and how to spend it wisely.',
    body: 'Full article content breaking down Tanzania safari costs. A budget camping safari in the Northern Circuit can run $150-250 per person per day, while a premium Western Circuit fly-in trip with chimpanzee trekking often starts around $600-900 per day once charter flights and park fees are included. The biggest cost drivers are accommodation style (camping vs. lodge vs. luxury camp), group size, and whether charter flights are required to reach remote parks like Mahale and Katavi.',
    author: 'LifeGranted Adventures Team',
    category: 'Tips & Planning',
    tags: ['Budget', 'Trip Planning', 'Costs'],
    featured_image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&h=500&fit=crop',
    seo_title: 'How Much Does a Tanzania Safari Cost? A Real Breakdown',
    seo_description: 'A transparent breakdown of what a Tanzania safari really costs, region by region.',
    is_published: true,
    published_at: '2024-03-15T00:00:00Z',
    created_at: '2024-03-12T00:00:00Z',
  },
  {
    id: 'blog-4',
    slug: 'katavi-national-park',
    title: "Katavi National Park: Why Africa's Most Untouched Wilderness Is Worth It",
    excerpt: 'Massive hippo pools, huge buffalo herds, and almost no other tourists. Here is why Katavi deserves a place on your Tanzania itinerary.',
    body: "Full article content about Katavi National Park. Katavi is Tanzania's third-largest national park, yet it receives a tiny fraction of the visitors that flow through the Serengeti each year. In the dry season, the Katuma River shrinks to a handful of mud-wallow pools that pack in hundreds of hippos at a time, while buffalo herds numbering in the thousands move across the floodplains. Access is by light aircraft from Mwanza or Arusha, and most camps operate on a fly-in, all-inclusive basis.",
    author: 'LifeGranted Adventures Team',
    category: 'Destinations',
    tags: ['Katavi', 'Western Tanzania', 'Wildlife'],
    featured_image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=500&fit=crop',
    seo_title: "Katavi National Park: Why Africa's Most Untouched Wilderness Is Worth It",
    seo_description: 'Discover why Katavi National Park deserves a spot on your Tanzania safari itinerary.',
    is_published: true,
    published_at: '2024-02-28T00:00:00Z',
    created_at: '2024-02-25T00:00:00Z',
  },
]

function generateMockAvailability(): Record<string, TourAvailability[]> {
  const result: Record<string, TourAvailability[]> = {}
  const today = new Date()
  for (const tour of MOCK_TOURS) {
    const slots: TourAvailability[] = []
    for (let i = 0; i < 60; i++) {
      const date = new Date(today)
      date.setDate(today.getDate() + i)
      const remaining = 6 + (i % 3)
      slots.push({
        id: `avail-${tour.id}-${i}`,
        tour_id: tour.id,
        available_date: date.toISOString().split('T')[0],
        slots_total: 8,
        slots_remaining: remaining,
        price_override_usd: null,
      })
    }
    result[tour.id] = slots
  }
  return result
}

export const MOCK_AVAILABILITY = generateMockAvailability()

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-101',
    booking_ref: 'LGA-2025-01042',
    tour_id: 'tour-3',
    operator_id: 'op-2',
    tourist_id: 'mock-user',
    tourist_name: 'Demo Traveler',
    tourist_email: 'demo@example.com',
    tourist_phone: '+1 555 010 0101',
    tourist_whatsapp: '+1 555 010 0101',
    tourist_nationality: 'US',
    group_size: 2,
    travel_date: '2026-08-12',
    special_requests: null,
    dietary_requirements: null,
    medical_notes: null,
    addons: [],
    total_usd: 6900,
    platform_fee_usd: 828,
    operator_payout_usd: 6072,
    booking_fee_usd: 262.2,
    charged_to_tourist_usd: 7162.2,
    payment_status: 'paid',
    payment_method: 'card',
    booking_status: 'confirmed',
    flutterwave_tx_ref: null,
    payout_released: false,
    created_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'bk-102',
    booking_ref: 'LGA-2024-00871',
    tour_id: 'tour-1',
    operator_id: 'op-1',
    tourist_id: 'mock-user',
    tourist_name: 'Demo Traveler',
    tourist_email: 'demo@example.com',
    tourist_phone: '+1 555 010 0101',
    tourist_whatsapp: '+1 555 010 0101',
    tourist_nationality: 'US',
    group_size: 2,
    travel_date: '2024-09-04',
    special_requests: null,
    dietary_requirements: null,
    medical_notes: null,
    addons: [],
    total_usd: 5600,
    platform_fee_usd: 672,
    operator_payout_usd: 4928,
    booking_fee_usd: 212.8,
    charged_to_tourist_usd: 5812.8,
    payment_status: 'paid',
    payment_method: 'card',
    booking_status: 'completed',
    flutterwave_tx_ref: null,
    payout_released: true,
    created_at: '2024-06-15T00:00:00Z',
  },
  {
    id: 'bk-103',
    booking_ref: 'LGA-2024-00512',
    tour_id: 'tour-4',
    operator_id: 'op-2',
    tourist_id: 'mock-user',
    tourist_name: 'Demo Traveler',
    tourist_email: 'demo@example.com',
    tourist_phone: '+1 555 010 0101',
    tourist_whatsapp: '+1 555 010 0101',
    tourist_nationality: 'US',
    group_size: 1,
    travel_date: '2024-03-10',
    special_requests: null,
    dietary_requirements: null,
    medical_notes: null,
    addons: [],
    total_usd: 320,
    platform_fee_usd: 38.4,
    operator_payout_usd: 281.6,
    booking_fee_usd: 12.16,
    charged_to_tourist_usd: 332.16,
    payment_status: 'refunded',
    payment_method: 'card',
    booking_status: 'cancelled',
    flutterwave_tx_ref: null,
    payout_released: false,
    created_at: '2024-02-01T00:00:00Z',
  },
]

export const MOCK_DISPUTES: Dispute[] = [
  {
    id: 'dis-1',
    booking_id: 'bk-1',
    booking_ref: 'LGA-2024-00871',
    tour_title: 'Mahale Mountains Chimpanzee Trek — 5 Days',
    operator_id: 'op-1',
    operator_name: 'Namiri Tours Mwanza',
    raised_by_id: null,
    raised_by_role: 'tourist',
    tourist_name: 'Sarah Mitchell',
    tourist_country: 'US',
    category: 'Quality Issue',
    description:
      'The boat transfer was delayed by 4 hours with no communication from the operator, which cut our first trekking day short. We were not offered any compensation for the lost time.',
    operator_response: null,
    status: 'open',
    resolution: null,
    resolved_by_id: null,
    resolved_at: null,
    created_at: '2025-06-10T00:00:00Z',
  },
  {
    id: 'dis-2',
    booking_id: 'bk-3',
    booking_ref: 'LGA-2024-00512',
    tour_title: 'Ngorongoro Crater Day Trip',
    operator_id: 'op-2',
    operator_name: 'Shayona Safaris Mwanza',
    raised_by_id: null,
    raised_by_role: 'tourist',
    tourist_name: 'Demo Traveler',
    tourist_country: 'US',
    category: 'Cancellation',
    description:
      'I cancelled 20 days before travel due to a family emergency and was only offered a 50% refund. I believe this should be reviewed given the circumstances.',
    operator_response: 'We followed the standard cancellation policy shown at booking, but are open to a goodwill gesture given the circumstances.',
    status: 'open',
    resolution: null,
    resolved_by_id: null,
    resolved_at: null,
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: 'dis-3',
    booking_id: 'bk-4',
    booking_ref: 'LGA-2024-00390',
    tour_title: 'Serengeti Great Migration Safari — 7 Days',
    operator_id: 'op-2',
    operator_name: 'Shayona Safaris Mwanza',
    raised_by_id: null,
    raised_by_role: 'tourist',
    tourist_name: 'Carlos Rivera',
    tourist_country: 'ES',
    category: 'No Show',
    description: 'Our guide did not show up at the agreed meeting point and we had to call the operator three times before someone arrived, 90 minutes late.',
    operator_response: 'We apologise for the delay — our guide had a vehicle breakdown. We offered an extra game drive as compensation, which the guests accepted.',
    status: 'resolved',
    resolution: '50% refund issued to tourist; operator coached on backup vehicle protocol.',
    resolved_by_id: 'admin-1',
    resolved_at: '2025-05-02T00:00:00Z',
    created_at: '2025-04-28T00:00:00Z',
  },
]

export function isSupabaseConfigured(): boolean {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  return !!url && !url.includes('placeholder')
}

